package com.tdd.hhplus_tdd_2week_java.domain.studuent;

public enum STUDENT_STATUS {
    VALUE_IS_NULL,
    INVALID_STUDENT_NAME,
    INVALID_STUDENT_CODE,

    INVALID_STUDENT_CODE_YEAR,

    NOT_EXIST_MAJOR,

    INVALID_STUDENT_NUMBER,
    NOT_ENOUGH_FIELD,

    NOT_EXIST_STUDENT,
    ALREADY_EXIST
}
