version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: xiuki-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Ssw!234!234
      MYSQL_DATABASE: init
      MYSQL_USER: xiuki
      MYSQL_PASSWORD: Ssw!234!234
    ports:
      - "33306:3306"
    volumes:
      - /Users/maxxing/Documents/GIT-HUB/MIDDLE_SETTING/mysql/save:/var/lib/mysql 
    networks:
      - my-network

networks:
  my-network: